### PR TITLE
[CS-39] Added an endpoint for getting the logged user info

### PR DESCRIPTION
**Pull request by BlueForeverI**

### CODE REVIEW

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BlueForeverI** [comment]
[Add user info on navigation bar](https://trello.com/c/TS7BfPK2/39-add-user-info-on-navigation-bar)

**Comment by BobbyBorisov** [comment]
:D това за кой task се отнася Жоци?

**Pull request merged**
